spec:
  containers:
  - name: instance-20240604-082923
    image: asia-northeast1-docker.pkg.dev/vivid-willow-381410/perforce-server/x-tech-perforce:1.0.5
    volumeMounts:
    - name: perforce-data
      readOnly: false
      mountPath: /opt/perforce/servers
    securityContext:
      privileged: true
    stdin: false
    tty: false
  volumes:
  - name: perforce-data
    gcePersistentDisk:
      pdName: perforce-data
      fsType: ext4
      partition: 0
      readOnly: false
  restartPolicy: Always
# This container declaration format is not public API and may change without notice. Please
# use gcloud command-line tool or Google Cloud Console to run Containers on Google Compute Engine."