spec:
  containers:
  - name: instance-20240604-082923
    image: perforce-server/x-tech-perforce
    volumeMounts:
    - name: host-path-0
      readOnly: false
      mountPath: /opt/perforce/servers/
    securityContext:
      privileged: true
    stdin: false
    tty: false
  volumes:
  - name: host-path-0
    hostPath:
      path: $PWD/storage/perforce
  restartPolicy: Always
# This container declaration format is not public API and may change without notice. Please
# use gcloud command-line tool or Google Cloud Console to run Containers on Google Compute Engine."